### ISSUE TITLE
Support for imagePullSecrets

### ISSUE THREAD

**Issue by brettmorien** [indeedeng-alpha/harbor-container-webhook#10]
I'm attempting to use the Harbor Webhook to utilize a secured Harbor instance. Replacement of the image source should be transparent to the user, so the Webhook should supply the `imagePullSecret`. This is different than the current Dynamic Proxy mechanism utilizing the `HARBOR_USER` and `HARBOR_PASS` variables.

This could be implemented with a similar mechanism of supplying these values in the Helm chart, however I'm currently seeing those values reflected in the clear in the installed helm chart. More ideally would be to accept a secret name+namespace structured similarly, and leave it to the user to create the secret.

**Comment by cnmcavoy** [comment]
How do you envision this working? The webhook is mutating pods, which are allowed to have many containers. More than container may match a rewrite directive. Multiple directives may match a single pod. I'm not sure in this situation what the right action for the webhook would be.

**Comment by brettmorien** [comment]
We actually went another route by setting up a proxy service to translate unauthenticated repository calls to authenticated calls to Harbor. The webhook was able to stay unchanged and we just point it to a different endpoint. I'm not sure how this would work integrated into the webhook either.
