### ISSUE TITLE
Prometheus ServiceMonitor

### ISSUE THREAD

**Issue by z0rc** [indeedeng-alpha/harbor-container-webhook#17]
As the webhook exposes prometheus metrics, it would be awesome if helm chart could deploy ServiceMonitor resource, so prometheus operator could autodiscover webhook scaping endpoints. https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/getting-started.md

**Comment by cnmcavoy** [comment]
If you want to submit one in a PR, I'll take a look. Otherwise I will look into this myself next time I make a release, which may be a while, as this webhook is feature complete at present.
