### ISSUE TITLE
single level repositories

### ISSUE THREAD

**Issue by babumiriyala** [indeedeng-alpha/harbor-container-webhook#28]
Hi,

is this below rule also pull single level repositories ? which need to have  ‘library’ namespace. 

reference - https://goharbor.io/docs/2.4.0/administration/configure-proxy-cache/

`rules:
  - name: 'docker.io rewrite rule'
    matches:
      - '^docker.io'
    excludes: []
    replace: 'harbor.example.com/dockerhub-proxy'`

**Comment by cnmcavoy** [comment]
"/library" (either its absence or presence) is automatically detected and remapped for images in the library namespace. Harbor container webhook uses the official containers golang sdk library, which handles remapping these names. The unit tests have coverage which ensure this functionality works.
