### ISSUE TITLE
Kubernetes min version incompatible with cloud K8

### ISSUE THREAD

**Issue by brettmorien** [indeedeng-alpha/harbor-container-webhook#5]
The min version for the chart is set to Kubernetes >= 1.16. This works with vanilla Kubernetes, but runs into trouble with cloud Kube versions. EKS looks like 1.18.9-eks.2, while GKE looks like 1.16.4-gke.1.

This can be fixed by updating the semver to accept "prelease" suffixes.
`kubeVersion: ">= 1.16.0-0"`

**Comment by brettmorien** [comment]
Documentation on others with this issue: https://github.com/kubernetes/kubernetes/issues/89404
This change shows the update:
https://github.com/brettmorien/harbor-container-webhook/commit/8e69e25046383d65ca5dba9a210901183b351038

**Comment by cnmcavoy** [comment]
Thanks for pointing this out! I updated the Chart information to include the prelease suffix.

**Comment by brettmorien** [comment]
Hi @cnmcavoy. We have started using Terraform helm_release instead of Rancher Apps for deploying parts and I've noticed this change is checked in, but not published to the chart repo. Can you push an updated Helm chart with this change in it? Thanks!
